// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6406.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6406.Robot;

/**
 *
 */
public class ClawOpen extends Command {

    public ClawOpen() {
        requires(Robot.claw);
    }
    @Override
    protected void execute() {
        Robot.claw.setOpen();
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return Robot.claw.getState();
    }
}
