// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc6406.subsystems;

import java.util.function.BooleanSupplier;

import org.usfirst.frc6406.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.Solenoid;


/**
 *
 */
public class claw extends Subsystem {
    boolean state = false;



    private final Solenoid cLaw_solenoid = RobotMap.clawCLaw_solenoid;


    @Override
    public void initDefaultCommand() {
        setClose();


        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    public void setOpen() {
        state = true;
        cLaw_solenoid.set(state);
    }

    public void setClose() {
        state = false;
        cLaw_solenoid.set(state);
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public boolean getState() {
        return state;
    }

}
